# Generated by Django 3.0.8 on 2020-07-18 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=80, null=True)),
                ('title', models.CharField(max_length=64)),
                ('location', models.CharField(default=None, max_length=64, null=True)),
                ('description', models.TextField(default=None, null=True)),
                ('employee_count', models.TextField(default=None, null=True)),
                ('test', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=64, null=True)),
                ('skills', models.TextField(default=None, null=True)),
                ('description', models.TextField(default=None, null=True)),
                ('salary_min', models.CharField(max_length=7)),
                ('salary_max', models.CharField(max_length=8)),
                ('published_at', models.CharField(max_length=30)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies',
                                              to='vacancy.Company')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies',
                                                to='vacancy.Specialty')),
            ],
        ),
    ]
