# Generated by Django 3.0.8 on 2020-07-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vacancy', '0002_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='employee_count',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='skills',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
