# Generated by Django 3.0.8 on 2020-08-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vacancy', '0010_auto_20200803_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default=None, height_field='height_field', null=True,
                                    upload_to='C:\\Users\\Xiaomi\\PythonProjects\\dj_projects\\stepik_vacancy\\media',
                                    width_field='width_field'),
        ),
    ]
