# Generated by Django 3.0.8 on 2020-08-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vacancy', '0012_auto_20200803_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='picture',
            field=models.ImageField(default=None, height_field='height_field', null=True, upload_to='picture',
                                    width_field='width_field'),
        ),
    ]
