# Generated by Django 3.0.8 on 2020-08-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0014_auto_20200808_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='height_field',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='width_field',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
